// generateTestResults.js
// This script aggregates individual test runner JSON outputs into a single test-results.json file.
// It reads all JSON files from the './temp-results' directory (you can configure the source directory),
// merges them into an array, and writes the combined results to './reports/test-results.json'.
// The schema matches the required fields for downstream Excel/HTML report generation.

const fs = require('fs');
const path = require('path');

// Directory containing individual test result JSON files (generated by various test runners)
const INPUT_DIR = path.resolve(__dirname, '..', 'temp-results');
// Output file path
const OUTPUT_FILE = path.resolve(__dirname, '..', 'reports', 'test-results.json');

function loadResults() {
  const results = [];
  if (!fs.existsSync(INPUT_DIR)) {
    console.warn(`Input directory ${INPUT_DIR} does not exist. No results to aggregate.`);
    return results;
  }
  const files = fs.readdirSync(INPUT_DIR);
  files.forEach(file => {
    if (file.endsWith('.json')) {
      try {
        const data = JSON.parse(fs.readFileSync(path.join(INPUT_DIR, file), 'utf8'));
        // Ensure each entry conforms to the required schema; fill missing keys with null.
        const normalized = data.map(entry => ({
          testId: entry.testId ?? null,
          category: entry.category ?? null,
          module: entry.module ?? null,
          testName: entry.testName ?? null,
          status: entry.status ?? null,
          startTime: entry.startTime ?? null,
          endTime: entry.endTime ?? null,
          duration: entry.duration ?? null,
          environment: entry.environment ?? null,
          browser: entry.browser ?? null,
          device: entry.device ?? null,
          errorMessage: entry.errorMessage ?? null,
          stackTrace: entry.stackTrace ?? null,
          screenshot: entry.screenshot ?? null,
          expectedResult: entry.expectedResult ?? null,
          actualResult: entry.actualResult ?? null,
        }));
        results.push(...normalized);
      } catch (e) {
        console.error(`Failed to parse ${file}: ${e.message}`);
      }
    }
  });
  return results;
}

function writeResults(results) {
  const outDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(results, null, 2), 'utf8');
  console.log(`Aggregated ${results.length} test results written to ${OUTPUT_FILE}`);
}

function main() {
  const aggregated = loadResults();
  writeResults(aggregated);
}

main();
